-- ============================================================
-- Kantun - početni podaci
-- Pokreni NAKON schema.sql (isti postupak: File -> Load SQL file -> F9)
-- ============================================================

SET NAMES utf8mb4;

-- ------------------------------------------------------------
-- Korisnici
-- Lozinke su spremljene kao bcrypt hash (nikad plain-text!).
--   Admin:    admin@kantun.hr    / Kantun2026!
--   Korisnik: iva.horvat@example.com / Korisnik123
-- ------------------------------------------------------------
INSERT INTO korisnici (ime, prezime, email, lozinka_hash, uloga) VALUES
('Admin', 'Kantun', 'admin@kantun.hr', '$2a$10$amLAKTGER.DnSmgpnPw5w.nQ1DV4HTuYISiCq50EvXQigxWouTaFG', 'admin'),
('Iva', 'Horvat', 'iva.horvat@example.com', '$2a$10$zH5ZJhOWYaUqcQGiYegtKus8ge5kKwUcvJ1T.grRmt7NJLU9Z2RQO', 'korisnik');

-- ------------------------------------------------------------
-- Kategorije
-- ------------------------------------------------------------
INSERT INTO kategorije (naziv, boja, ikona) VALUES
('Glazba', '#2dd4bf', 'music_note'),
('Kazalište', '#a78bfa', 'theater_comedy'),
('Izložbe', '#f59e0b', 'palette'),
('Gastronomija', '#f87171', 'restaurant'),
('Sport', '#60a5fa', 'sports_soccer'),
('Festivali', '#34d399', 'celebration');

-- ------------------------------------------------------------
-- Događanja
-- Ovo su STVARNI, trenutno najavljeni događaji u Rijeci, Opatiji i na
-- Krku (provjereno preko Entrio.hr, kolovoz 2026.) - ne izmišljeni demo
-- podaci. Cijena je kod većine postavljena na NULL ("nepoznato / provjeri
-- na poveznici") jer listing stranice ne prikazuju cijenu izravno - vidi
-- napomenu o koloni "cijena" u schema.sql. Ako s vremenom neki od ovih
-- događaja prođe ili se otkaže, jednostavno ga obriši/uredi kroz admin
-- panel, ili pokreni automatski uvoz (Admin -> Pregled -> "Uvezi evente")
-- da se popis osvježi stvarnim, trenutno aktualnim događanjima.
-- ------------------------------------------------------------
INSERT INTO dogadanja (naziv, opis, kategorija_id, lokacija, grad, adresa, datum_pocetka, datum_zavrsetka, cijena, slika_url, web_link) VALUES
('Ritam Promjena & Violetta Peppermint', 'Ljetni glazbeni spektakl na Trsatskoj gradini — Ritam Promjena nastupaju zajedno s Violettom Peppermint u sklopu bogatog kulturnog programa Rijeke. Ambijent srednjovjekovne tvrđave s pogledom na grad čini ovaj koncert posebnim doživljajem za sve ljubitelje domaće glazbene scene.', 1, 'Trsatska gradina', 'Rijeka', NULL, '2026-08-22 21:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800', 'https://www.entrio.hr/en/events/rijeka'),
('Vesna Pisarović - koncert', 'Vesna Pisarović, jedna od najprepoznatljivijih hrvatskih pjevačica, nastupa na otvorenom u Nugentovom parku Trsatskog kaštela. Očekuje se večer punog glasa i publike koja pjeva svaki stih zajedno s njom.', 1, 'Trsatski kaštel - Nugentov park', 'Rijeka', NULL, '2026-08-28 21:45:00', NULL, NULL, 'https://images.unsplash.com/photo-1603190287605-e6ade32fa852?w=800', 'https://www.entrio.hr/en/events/rijeka'),
('Stand-up: Nezgodna Situacija', 'Opuštena stand-up večer u Bačva Pubu donosi komičare koji se hvataju u koštac sa svakodnevnim "nezgodnim situacijama" iz života. Idealno za druženje uz smijeh i piće nakon radnog tjedna.', 2, 'Bačva Pub', 'Rijeka', NULL, '2026-08-29 20:30:00', NULL, NULL, 'https://images.unsplash.com/photo-1527261834078-9b37d35a4a32?w=800', 'https://www.entrio.hr/en/events/rijeka'),
('Buč Kesidi - koncert', 'Buč Kesidi ponovno pali pozornicu Trsatske gradine u sklopu ljetnog glazbenog ciklusa. Energičan nastup i prepoznatljiv stil pjevača privlače publiku svih generacija.', 1, 'Trsatska gradina', 'Rijeka', NULL, '2026-08-29 21:45:00', NULL, NULL, 'https://images.unsplash.com/photo-1682133114083-81319fc857fe?w=800', 'https://www.entrio.hr/en/events/rijeka'),
('Disco Revival: 80s & 90s', 'Disco Revival vraća atmosferu 80-ih i 90-ih na Trsatsku gradinu — hitovi koji su obilježili generacije, sad uživo pod zvijezdama. Plesni podij otvoren je cijelu večer za sve nostalgičare.', 1, 'Trsatska gradina', 'Rijeka', NULL, '2026-09-04 19:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800', 'https://www.entrio.hr/en/events/rijeka'),
('Nije Smešno, Žarko!', 'Komičarska predstava "Nije Smešno, Žarko!" u HKD Sušak kombinira oštar humor i društvenu satiru. Večer je namijenjena publici koja voli komediju s malo više zajedljivosti.', 2, 'HKD Sušak', 'Rijeka', NULL, '2026-09-09 20:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1585347110520-7a8a5c77af09?w=800', 'https://www.entrio.hr/en/events/rijeka'),
('Vlatko Štampar - Stand-up Comedy', 'Vlatko Štampar donosi svoj prepoznatljiv stand-up program na pozornicu HKD Sušak. Iskusni komičar zabavlja publiku pričama iz svakodnevice, uz puno improvizacije.', 2, 'HKD Sušak', 'Rijeka', NULL, '2026-09-16 20:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1541592553160-82008b127ccb?w=800', 'https://www.entrio.hr/en/events/rijeka'),
('Andrija Milošević - Stand-up', 'Andrija Milošević nastupa s novim stand-up materijalom u HKD Sušak. Večer opuštenog humora za sve koji trebaju dobar razlog za smijeh.', 2, 'HKD Sušak', 'Rijeka', NULL, '2026-10-02 20:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1507676385008-e7fb562d11f8?w=800', 'https://www.entrio.hr/en/events/rijeka'),
('Sonas X', 'Sonas X donosi klupsku glazbenu večer u prostoru POGON-a, s fokusom na elektroničku i klupsku scenu Rijeke. Idealno za one koji traže nešto drugačije od klasičnog koncertnog ugođaja.', 1, 'POGON', 'Rijeka', NULL, '2026-10-09 21:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800', 'https://www.entrio.hr/en/events/rijeka'),
('Alterna - House of Carnival', 'House of Carnival okuplja ljubitelje klupske glazbe u Export drvu, uz DJ-eve i gostujuće izvođače iz regije. Noć je predviđena za ples do kasno.', 1, 'Export drvo', 'Rijeka', NULL, '2026-10-10 21:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1522158637959-30385a09e0da?w=800', 'https://www.entrio.hr/en/events/rijeka'),
('Anđelka u Rijeci', 'Predstava "Anđelka u Rijeci" na pozornici HKD-a na Sušaku donosi komediju s prepoznatljivim likovima i duhovitim dijalozima. Zabavna večer za sve generacije.', 2, 'Hrvatski kulturni dom na Sušaku', 'Rijeka', NULL, '2026-10-12 20:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1578337834535-357ad7dccdfd?w=800', 'https://www.entrio.hr/en/events/rijeka'),
('Penzići Luduju', 'Komedija "Penzići Luduju" prati duhovite peripetije skupine umirovljenika u potrazi za avanturom. Predstava puna smijeha na pozornici Hrvatskog kulturnog doma na Sušaku.', 2, 'Hrvatski kulturni dom na Sušaku', 'Rijeka', NULL, '2026-11-13 20:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1705944601101-fdb49dbf884c?w=800', 'https://www.entrio.hr/en/events/rijeka'),
('URBAN&4 - koncert', 'URBAN&4 nastupaju na Ljetnoj pozornici u Opatiji u sklopu ljetnog glazbenog programa Kvarnera. Otvoreni prostor uz more stvara poseban ugođaj za koncert.', 1, 'Ljetna pozornica u Opatiji', 'Opatija', NULL, '2026-08-22 21:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1509824227185-9c5a01ceba0d?w=800', 'https://www.entrio.hr/en/events/opatija'),
('24. Liburnia Film Festival', '24. izdanje Liburnia Film Festivala donosi nekoliko dana filmskih projekcija na otvorenom te popratni program u Opatiji. Festival već tradicionalno okuplja ljubitelje filma iz cijele regije.', 6, 'Mala ljetna pozornica Opatija', 'Opatija', NULL, '2026-08-25 20:00:00', '2026-08-29 23:00:00', NULL, 'https://images.unsplash.com/photo-1742047959980-2cf34dfb9552?w=800', 'https://www.entrio.hr/en/events/opatija'),
('Psi pod zvijezdama', '"Psi pod zvijezdama" je večernji program na otvorenom u Opatiji, zamišljen kao opušteno druženje uz glazbu i noćni ugođaj Male ljetne pozornice.', 6, 'Mala ljetna pozornica u Opatiji', 'Opatija', NULL, '2026-09-01 20:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1690259424579-a99d5bd49be3?w=800', 'https://www.entrio.hr/en/events/opatija'),
('Orašar - baletni spektakl', 'Baletni spektakl "Orašar" stiže u opatijski Centar Gervais s klasičnom božićnom pričom u plesnoj izvedbi. Prigodan je izbor za obiteljski izlazak krajem godine.', 2, 'Centar Gervais', 'Opatija', NULL, '2026-12-08 20:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1609039504401-47ac3940f378?w=800', 'https://www.entrio.hr/en/events/opatija'),
('KOKE - koncert', 'Bend KOKE nastupa u kinu Krk uz svoj prepoznatljiv zvuk domaće glazbene scene. Manji, intimniji prostor kina donosi bliži kontakt s publikom.', 1, 'Kino Krk', 'Krk', NULL, '2026-08-21 21:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1450044804117-534ccd6e6a3a?w=800', 'https://www.entrio.hr/en/events/krk'),
('Vau Vau Zvijezda 3: Bitka bendova', 'Vau Vau Zvijezda 3: Bitka bendova je natjecateljski glazbeni show u kinu Krk gdje se mladi bendovi bore za pobjedu pred publikom i žirijem. Odlična je prilika za otkrivanje nove glazbene scene otoka.', 6, 'Kino Krk', 'Krk', NULL, '2026-08-29 10:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1698180918987-30bd75410473?w=800', 'https://www.entrio.hr/en/events/krk');

-- ------------------------------------------------------------
-- Događanja - rujan 2026 (dodatna događanja da kalendar bude
-- popunjen za cijeli mjesec; datumi/lokacije prikupljeni iz javno
-- najavljenog programa kazališta/koncertnih dvorana u Rijeci i
-- Opatiji, opisi su samostalno napisani)
-- ------------------------------------------------------------
INSERT INTO dogadanja (naziv, opis, kategorija_id, lokacija, grad, adresa, datum_pocetka, datum_zavrsetka, cijena, slika_url, web_link) VALUES
('Otvorenje jesenske koncertne sezone u Klubu Palach', 'Nova koncertna sezona u Klubu Palach kreće energično uz punk nastupe grupa Motus Vita Est, Tahijevi Kmetovi, Insomnia i Mitraljez. Dvije generacije riječke punk scene dijele istu pozornicu jedne večeri.', 1, 'Klub Palach', 'Rijeka', NULL, '2026-09-04 20:00:00', NULL, 8, 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800', NULL),
('Kathy Kelly & Band', 'Kathy Kelly, poznata po glazbenoj obitelji The Kelly Family, dolazi u Opatiju s koncertnim programom koji spaja stare hitove i pjesme sa svoje solo karijere. Večer intimnog i zrelog glazbenog izričaja na Ljetnoj pozornici.', 1, 'Ljetna pozornica u Opatiji', 'Opatija', NULL, '2026-09-04 20:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1603190287605-e6ade32fa852?w=800', NULL),
('Candlelight: Coldplay vs. Imagine Dragons', 'Gudački kvartet u Hotelu Kvarner izvodi najveće hitove Coldplaya i Imagine Dragonsa uz svjetlo svijeća. Elegantne klasične aranžmane poznatih pjesama poput "Clocks" i "Believer" prati poseban, intiman ugođaj.', 1, 'Hotel Kvarner', 'Opatija', NULL, '2026-09-05 21:00:00', NULL, 23, 'https://images.unsplash.com/photo-1682133114083-81319fc857fe?w=800', 'https://feverup.com/m/667157'),
('The Amy Winehouse Band', 'Originalni glazbenici koji su godinama svirali uz Amy Winehouse dolaze na Trsat s večeri posvećenom njezinoj glazbi. Očekuju se bezvremenski hitovi poput "Rehab" i "Valerie", uz DJ set prije i poslije koncerta.', 1, 'Trsatska gradina - Nugentov park', 'Rijeka', NULL, '2026-09-12 20:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800', NULL),
('Tukico - otvorenje programa Japan u Rijeci', 'Japanska violinistica i multiinstrumentalistica Tukico (Hoshiko Yamane), dugogodišnja članica Tangerine Dream, otvara program "Japan u Rijeci" ekskluzivnim nastupom u MMSU-u. Gradi hipnotičke zvučne krajolike uživo pomoću električne viole i loop pedala.', 1, 'Muzej moderne i suvremene umjetnosti (MMSU)', 'Rijeka', NULL, '2026-09-14 21:00:00', NULL, 15, 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800', NULL),
('Hibiki Kojima plays Ryuichi Sakamoto', 'Mladi japanski pijanist Hibiki Kojima zatvara program "Japan u Rijeci" koncertom posvećenim Ryuichiju Sakamotu i glazbi iz video igara poput Final Fantasyja i Zelde. Nastup spaja filmsku melankoliju s modernom pop kulturom.', 1, 'Hrvatski kulturni dom na Sušaku (HKD)', 'Rijeka', NULL, '2026-09-21 21:00:00', NULL, 10, 'https://images.unsplash.com/photo-1522158637959-30385a09e0da?w=800', 'https://core-event.co/en/events/hibiki-kojima-japan-u-rijeci-2026-0b8e/'),
('The Romans & friends @ Pogon', 'Zagrebački bend The Romans slavi izdanje vinilne verzije albuma "Dandelion" koncertom u Pogonu, uz brojne glazbene goste na pozornici. Nakon koncerta slijedi DJ set i ples do kasno.', 1, 'Pogon Kulture', 'Rijeka', NULL, '2026-09-25 21:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1509824227185-9c5a01ceba0d?w=800', NULL),
('Beatles Revival Orchestra', 'Veliki simfonijski hommage Beatlesima spaja rock bend, Riječki simfonijski orkestar i Operni zbor u jednoj večeri. Bezvremenske pjesme dobivaju novi, orkestralni sjaj na pozornici HNK Ivana pl. Zajca.', 1, 'Hrvatsko narodno kazalište Ivana pl. Zajca', 'Rijeka', NULL, '2026-09-09 19:30:00', NULL, NULL, 'https://images.unsplash.com/photo-1450044804117-534ccd6e6a3a?w=800', 'https://www.mojekarte.hr/hr/beatles-revival-orchestra/ulaznice-651096.html'),
('ČVOR - Kolektiv Igralke & Žiga Divjak', 'Predstava "Čvor", nastala u suradnji Kolektiva Igralke i slovenskog redatelja Žige Divjaka, propituje što se događa kad se priprema za rat počne predstavljati kao jedini razuman način zaštite budućnosti. Kroz niz osobnih situacija istražuje kako veliki politički procesi ulaze u svakodnevni život.', 2, 'Hrvatsko narodno kazalište Ivana pl. Zajca', 'Rijeka', NULL, '2026-09-05 19:30:00', NULL, NULL, 'https://images.unsplash.com/photo-1527261834078-9b37d35a4a32?w=800', 'https://www.mojekarte.hr/hr/kolektiv-igralke-cvor/ulaznice-651061.html'),
('Ovlaštene za zaštitu', 'Performans-instalacija koja dokumentarnim pristupom istražuje iskustva žena i majki u kontekstu militarizacije i ratnih okolnosti, temeljena na stvarnim svjedočanstvima iz cijele Europe. Kombinira izvedbu, video, zvuk i instalaciju u prostoru SubLab scene HKD-a.', 2, 'Hrvatski kulturni dom na Sušaku (HKD)', 'Rijeka', NULL, '2026-09-05 20:00:00', NULL, 0, 'https://images.unsplash.com/photo-1585347110520-7a8a5c77af09?w=800', NULL),
("Angels' Orders - The Rilke Project", 'Site-specific izvedba nadahnuta Rilkeovom poezijom spaja ples i elektroničku glazbu uživo na Molo Longo. Ples se gradi kroz ponavljanje i slušanje u stvarnom vremenu, pretvarajući poeziju u fizičko i kolektivno iskustvo.', 2, 'Molo Longo', 'Rijeka', NULL, '2026-09-07 20:00:00', NULL, 0, 'https://images.unsplash.com/photo-1541592553160-82008b127ccb?w=800', NULL),
('Your Play - Riječko kazalište mladih', 'Riječko kazalište mladih izvodi satiričnu predstavu o izmišljenoj državi Experimentiji, na engleskom jeziku s hrvatskim titlovima. Komedija apsurda progovara o političkom populizmu, potrošačkom društvu i iseljavanju mladih.', 2, 'Hrvatski kulturni dom na Sušaku (HKD)', 'Rijeka', NULL, '2026-09-08 20:00:00', NULL, 0, 'https://images.unsplash.com/photo-1507676385008-e7fb562d11f8?w=800', NULL),
('KAZALIŠTE - Pascal Rambert', 'Francuski dramatičar i redatelj Pascal Rambert napisao je predstavu posebno za riječki ansambl HNK Ivana pl. Zajca, nadahnutu razgovorima sa svakim glumcem pojedinačno. Nastaje intimna priča o ljubavi prema kazalištu i svakodnevici glumaca unutar jednog ansambla.', 2, 'Hrvatsko narodno kazalište Ivana pl. Zajca', 'Rijeka', NULL, '2026-09-10 19:30:00', NULL, NULL, 'https://images.unsplash.com/photo-1578337834535-357ad7dccdfd?w=800', 'https://www.mojekarte.hr/hr/kazaliste/ulaznice-651063.html'),
('TO=TO', 'Peti ansambl i CO2… par umjetnika donose izvedbu nadahnutu djelom danske spisateljice Inger Christensen, na Tržnici Brajda. Predstava o osam dana stvaranja istražuje što se događa kad se uobičajeni sustavi privremeno suspendiraju.', 2, 'Tržnica Brajda', 'Rijeka', NULL, '2026-09-11 20:00:00', '2026-09-12 21:10:00', NULL, 'https://images.unsplash.com/photo-1705944601101-fdb49dbf884c?w=800', 'https://www.mojekarte.hr/hr/to-to/ulaznice-651076.html'),
('Iva i Gloria', 'Komedija o dvjema prijateljicama koje rade kao čistačice u kazalištu, ali ne odustaju od sna da postanu glumice, stiže na Ljetnu pozornicu u Opatiji. Duhovita i pomalo gorko-slatka priča o prijateljstvu, obitelji i snovima koje nosimo kroz život.', 2, 'Ljetna pozornica u Opatiji', 'Opatija', NULL, '2026-09-12 19:30:00', NULL, NULL, 'https://images.unsplash.com/photo-1609039504401-47ac3940f378?w=800', 'https://www.eventim.hr/artist/iva-i-gloria/predstava-iva-i-glora-4212329/'),
('Ovo (ni)je naš grad', 'Srednjoškolska drama grupa Pontes izvodi predstavu nadahnutu Brechtovom "Operom za tri groša", o granicama između kriminala i vlasti. Predstava postavlja pitanje tko stvara pravila, a tko ih koristi za osobnu korist.', 2, 'Hrvatski kulturni dom na Sušaku (HKD)', 'Rijeka', NULL, '2026-09-14 20:00:00', NULL, 8, 'https://images.unsplash.com/photo-1527261834078-9b37d35a4a32?w=800', 'https://www.mojekarte.hr/hr/ovo-ni-je-nas-grad/ulaznice-650949.html'),
('Kabanica', 'Predstava prema poznatoj pripovijetci Nikolaja Gogolja o skromnom činovniku čiji se život mijenja zbog potrebe za novim kaputom. Satira o birokraciji i osamljenosti ostaje jednako aktualna i danas.', 2, 'Hrvatski kulturni dom na Sušaku (HKD)', 'Rijeka', NULL, '2026-09-15 20:00:00', NULL, 8, 'https://images.unsplash.com/photo-1585347110520-7a8a5c77af09?w=800', 'https://www.mojekarte.hr/hr/kabanica/ulaznice-650950.html'),
('Turandot - Giacomo Puccini', 'Nakon 32 godine HNK Ivana pl. Zajca vraća na pozornicu Puccinijevu posljednju operu "Turandot", uz Riječki simfonijski orkestar i Operni zbor. Nova produkcija francuskog redatelja Arnauda Bernarda izvodi se dva puta, 16. i 18. rujna.', 2, 'Hrvatsko narodno kazalište Ivana pl. Zajca', 'Rijeka', NULL, '2026-09-16 19:00:00', '2026-09-18 21:45:00', NULL, 'https://images.unsplash.com/photo-1541592553160-82008b127ccb?w=800', 'https://www.mojekarte.hr/'),
('Klammov rat', 'Gostujuća predstava Teatra EXIT donosi monodramu njemačkog dramatičara Kaija Hensela o profesoru književnosti kojem se razred zavjerio šutnjom. Psihološki intenzivna priča o izgubljenoj komunikaciji i empatiji u obrazovnom sustavu.', 2, 'Hrvatsko narodno kazalište Ivana pl. Zajca', 'Rijeka', NULL, '2026-09-17 19:30:00', NULL, NULL, 'https://images.unsplash.com/photo-1507676385008-e7fb562d11f8?w=800', 'https://hnk-zajc.mojekarte.hr/hr/gostovanje-teatar-exit-klammov-rat/ulaznice-651072.html'),
('Wetware - Jan Rozman', 'Slovenski koreograf i izvođač Jan Rozman spaja stand-up, koreografiju i suvremenu teoriju u duhovitoj predstavi o tijelu, tehnologiji i društvu. Propituje tjelesnu autonomiju u doba pametnih uređaja i algoritama koji nas prate.', 2, 'Hrvatski kulturni dom na Sušaku (HKD)', 'Rijeka', NULL, '2026-09-17 20:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1578337834535-357ad7dccdfd?w=800', 'https://hkd-rijeka.hr/dogadanja/wetware-jan-rozman/'),
('Zakopana čuda', 'Multimedijalna predstava Monike Herceg, u režiji Nine Violić, prati posljednje trenutke života jedne žene kroz tri simbolična prostora - vrt, most i stan. Video projekcije i glazba stvaraju slojevito, filmično kazališno iskustvo o ljubavi i sjećanju.', 2, 'Hrvatsko narodno kazalište Ivana pl. Zajca', 'Rijeka', NULL, '2026-09-18 19:00:00', NULL, NULL, 'https://images.unsplash.com/photo-1705944601101-fdb49dbf884c?w=800', 'https://www.mojekarte.hr/hr/zakopana-cuda/ulaznice-651075.html'),
('Moj balon i ja', 'Suvremeni plesni solo Tamare Bračun istražuje prostor između težine i lakoće, kroz pokret, tišinu i dah. Nastup poziva publiku da zastane i pronađe vlastita značenja unutar plesa.', 2, 'Hrvatski kulturni dom na Sušaku (HKD)', 'Rijeka', NULL, '2026-09-19 20:00:00', NULL, 0, 'https://images.unsplash.com/photo-1609039504401-47ac3940f378?w=800', NULL),
('Premijera: Idiot', 'Redatelj Janusz Kica i dramatičar Ivor Martinić donose suvremenu dramsku adaptaciju remek-djela Dostojevskog "Idiot". Predstava propituje može li dobrota preživjeti u svijetu koji često nagrađuje suprotne vrijednosti.', 2, 'Hrvatsko narodno kazalište Ivana pl. Zajca', 'Rijeka', NULL, '2026-09-25 19:30:00', NULL, NULL, 'https://images.unsplash.com/photo-1541592553160-82008b127ccb?w=800', 'https://www.mojekarte.hr/hr/premijera-idiot/ulaznice-651066.html'),
('Radikalna subjektivnost: Katalin Ladik i Tomaso Binga', 'Velika dvostruka samostalna izložba mađarske umjetnice Katalin Ladik i talijanske umjetnice Tomaso Binge u MMSU-u istražuje odnos jezika, tijela i glasa kroz vizualnu poeziju i performans. Dio radova po prvi puta se predstavlja hrvatskoj publici, uz jedinstvenu seriju fotografija Ladikinog nastupa u Rijeci iz 1970. godine.', 3, 'Muzej moderne i suvremene umjetnosti (MMSU)', 'Rijeka', NULL, '2026-07-18 10:00:00', '2026-09-21 20:00:00', 0, 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800', NULL),
('Grobnik Open Ski Roll 26 - Žiletov memorijal', 'Riječko-čavaljski trkački skijaški klub organizira 26. izdanje međunarodne utrke na koturaljkama za skijaško trčanje na Platku, koja nosi status Hrvatskog prvenstva u ovoj disciplini. Cesta od Lujzinske ceste do parkirališta na Platku bit će privremeno zatvorena za promet.', 5, 'Platak', 'Rijeka', NULL, '2026-09-13 10:00:00', '2026-09-13 13:00:00', 0, 'https://images.unsplash.com/photo-1584907600887-9732fa3647ac?w=800', NULL),
('Drenova Trail 2026', 'Jedanaesto izdanje trail utrke vodi kroz šume iznad Rijeke, uz Veli Vrh i kanjon Rječine, s pogledom na Kvarner i Grobnik. Sudionici biraju stazu od 10 ili 30 kilometara, uz start na Cvetkovom trgu u Drenovi.', 5, 'Cvetkov trg - Drenova', 'Rijeka', NULL, '2026-09-19 10:00:00', NULL, 30, 'https://images.unsplash.com/photo-1560354790-a403c5a97e0f?w=800', NULL),
('Opatija ponovno trči za srce', 'Peto izdanje humanitarne utrke "Trči za srce", dio programa Dana srca u Opatiji, nudi trase od 5 i 10 kilometara za sve generacije. Sudjeluju i psi uz odgovoran nadzor vlasnika, a prikupljena sredstva idu u humanitarne svrhe.', 5, 'Slatina', 'Opatija', NULL, '2026-09-26 10:00:00', NULL, 0, 'https://images.unsplash.com/photo-1530143311094-34d807799e8f?w=800', 'https://danisrca.com'),
('Dark Circle Fest XIII', 'Trinaesto izdanje najmračnijeg regionalnog festivala u Klubu Palach donosi dva dana s 12 pažljivo odabranih bendova metal i rock scene. Uz glazbeni program tu je i tradicionalni Glam Floor te humanitarna akcija za sklonište za pse u Viškovu.', 6, 'Klub Palach', 'Rijeka', NULL, '2026-09-11 20:00:00', '2026-09-13 03:00:00', 18, 'https://images.unsplash.com/photo-1742047959980-2cf34dfb9552?w=800', NULL);

-- ------------------------------------------------------------
-- Favoriti (demo korisnik Iva je spremila par događanja)
-- ------------------------------------------------------------
INSERT INTO favoriti (korisnik_id, dogadanje_id) VALUES
(2, 1),
(2, 3);

-- ------------------------------------------------------------
-- Rezervacije (demo korisnik Iva je rezervirala mjesta)
-- ------------------------------------------------------------
INSERT INTO rezervacije (korisnik_id, dogadanje_id, broj_mjesta, status) VALUES
(2, 2, 2, 'potvrdena'),
(2, 5, 1, 'na_cekanju');
